###############################################################################
# Configuration properties for the framework
#
# - Default global config values
# - Default file names ()
# - Connection string values {may require separate config file!?}
#
###############################################################################

#==============================================================================
# Global Configuration
#==============================================================================
defaultBrowser=Chrome
#-- implicit wait in seconds
defaultImplicitWait=2
screenShotFlag=true
path2screenShotFolder=todo
excelConfigPath=todo
platform=Desktop

# ---> firefox options (& capabilities are obsolete but...)
# accept-ssl-cert=true

# ---> chrome options (& capabilities are obsolete but...)

# ---> edge options (& capabilities are obsolete but...)

#==============================================================================
# Files Configuration
#==============================================================================
# chromeDriverPath=
# edgeDriverPath=
# operaDriverPath=

#==============================================================================
# DB Configuration
#==============================================================================
# ---> SQL Server values
# server=
# database=
# timeout=
# user=
# password=

# ---> Oracle values
# todo?

# ---> Other engines
# todo?